# Generated by Django 6.0.1 on 2026-01-21 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=40)),
                ('Product_ID', models.CharField(max_length=10)),
                ('Product_Category', models.CharField(choices=[('ELE', 'Electronics'), ('FAS', 'Fashion & Apparel'), ('BEA', 'Beauty & Personal Care'), ('HOM', 'Home & Living'), ('GRO', 'Groceries & Essentials'), ('BOO', 'Books & Stationery'), ('SPO', 'Sports & Fitness'), ('TOY', 'Toys & Games'), ('HEA', 'Health & Wellness'), ('AUT', 'Automotive'), ('FUR', 'Furniture'), ('JEW', 'Jewelry & Accessories'), ('PET', 'Pet Supplies'), ('OFF', 'Office Supplies'), ('DIG', 'Digital Products')], max_length=3)),
                ('Product_Description', models.TextField()),
                ('Image_one', models.URLField()),
                ('Image_two', models.URLField()),
                ('Image_three', models.URLField()),
                ('Image_four', models.URLField()),
                ('Image_five', models.URLField()),
                ('Seller_Address', models.TextField()),
                ('Price', models.PositiveIntegerField(default=10)),
                ('Bought_Date', models.DateTimeField()),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Updated_Date', models.DateTimeField(auto_now=True)),
                ('Seller_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
