# Generated by Django 6.0.1 on 2026-01-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Bought_Date',
            field=models.DateTimeField(),
        ),
    ]
