# Generated by Django 6.0.1 on 2026-01-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.URLField(default='https://i.pinimg.com/1200x/6e/59/95/6e599501252c23bcf02658617b29c894.jpg')),
                ('Country_Code', models.CharField(default='+977', max_length=5)),
                ('Phone_Number', models.CharField(default='9800000000', max_length=10)),
                ('Address', models.TextField()),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
