# Generated by Django 6.0 on 2025-12-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_Image', models.ImageField(upload_to='', verbose_name='/products')),
                ('Prod_Name', models.CharField(max_length=30)),
                ('Prod_Rate', models.IntegerField()),
            ],
        ),
    ]
