# Generated by Django 6.0 on 2025-12-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Prod_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
