# Generated by Django 6.0.1 on 2026-01-18 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyers_Username', models.CharField(max_length=30)),
                ('Product_Name', models.CharField(max_length=30)),
                ('Product_Description', models.TextField()),
                ('Product_Category', models.CharField(max_length=3)),
                ('Price', models.PositiveIntegerField()),
                ('Paid', models.BooleanField(default=True)),
                ('Payment_Time', models.DateTimeField(auto_now_add=True)),
                ('Buyers_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
