# Generated by Django 6.0.1 on 2026-01-17 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.URLField()),
                ('Country_Code', models.CharField(choices=[('Nepal', '+977'), ('India', '+91'), ('United States', '+1'), ('United Kingdom', '+44'), ('Canada', '+1'), ('Australia', '+61'), ('Germany', '+49'), ('France', '+33'), ('United Arab Emirates', '+971'), ('Saudi Arabia', '+966'), ('Japan', '+81'), ('South Korea', '+82')], default='+977', max_length=30)),
                ('Phone_Number', models.CharField(default='9800000000', max_length=10)),
                ('Address', models.TextField()),
                ('Username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
